Common: &common
  tokenizer: /home/ubuntu/.cache/ckpts/nv-embedqa-e5-v5_v5
  tokenizer_max_seq_len: 512
  model: /home/ubuntu/.cache/engines/nv-embedqa-e5-v5_v5/tensorrt
  served_model_name: nvidia/nv-embedqa-e5-v5
  block-size: 64
  max-model-len: 16384

Frontend:
  <<: *common
  endpoint: dynamo.Processor.embed
  port: 8000

Processor:
  <<: *common

TrtWorkerEmbedding:
  <<: *common
  embedding_dim: 1024

# VllmWorker:
#   enforce-eager: true
#   max-num-batched-tokens: 16384
#   enable-prefix-caching: true
#   router: random
#   tensor-parallel-size: 1
#   ServiceArgs:
#     workers: 1
#     resources:
#       gpu: 1
#   common-configs: [model, block-size, max-model-len]
